[package]
name = "parser"
version = "0.0.0"
edition = "2024"

[dependencies]
kdl = { workspace = true }
derives = { workspace = true }
smart-default = { workspace = true }
serde = { workspace = true }
getset-macro = { workspace = true }
node = { workspace = true }
#progress = { workspace = true }
#TODO: use crate::data::markup::{entry::NodeEntryState, essay::read_kdl, node::NodeState};
