
[package]
name = "node"
version = "0.0.0"
edition = "2024"

[dependencies]
derives = { workspace = true }
kdl = { workspace = true }
getset-macro = { workspace = true }
thiserror = { workspace = true }
derive_more = { workspace = true }
serde = { workspace = true }
smart-default = { workspace = true }
